import React, { useEffect, useState } from 'react'
export default function Dashboard(){
  const [doctors, setDoctors] = useState([])
  const [byIns, setByIns] = useState({})
  const [insList, setInsList] = useState([])
  useEffect(()=>{ setDoctors(JSON.parse(localStorage.getItem('doctorsList')||'[]')); setByIns(JSON.parse(localStorage.getItem('doctorsByInsurance')||'{}')); setInsList(JSON.parse(localStorage.getItem('insuranceList')||'[]')) },[])
  useEffect(()=>{ const onStorage=()=>{ setDoctors(JSON.parse(localStorage.getItem('doctorsList')||'[]')); setByIns(JSON.parse(localStorage.getItem('doctorsByInsurance')||'{}')); setInsList(JSON.parse(localStorage.getItem('insuranceList')||'[]')) }; window.addEventListener('storage', onStorage); const id=setInterval(onStorage,60*1000); return ()=>{ window.removeEventListener('storage', onStorage); clearInterval(id) } },[])
  const getDays = (date)=>{ if(!date) return null; const days = Math.ceil((new Date(date)-new Date())/(1000*60*60*24)); return days }
  return (<div className="max-w-6xl mx-auto"><section className="mt-6"><h2 className="text-sky-200 text-lg font-semibold mb-2">Insurance Overview</h2><div className="overflow-x-auto bg-card rounded p-4"><table className="min-w-full text-sm"><thead className="text-slate-300"><tr><th className="text-left p-2">Insurance</th><th className="p-2">Type</th><th className="p-2">Doctor</th><th className="p-2">Network</th><th className="p-2">Expiration</th><th className="p-2">Days Left</th><th className="p-2">Notes</th></tr></thead><tbody className="text-slate-200">{insList.map((i,idx)=>{ const days = getDays(i.expiration); const highlight = days!==null && days<=90 && days>0; return (<tr key={i.id||idx} className={`border-t border-slate-800 ${highlight? 'bg-[#5b3e8d]':''}`}><td className="p-2">{i.name}</td><td className="p-2">{i.type}</td><td className="p-2">{i.doctor? i.doctorName || i.doctor : ''}</td><td className="p-2">{i.network==='In Network'? <span className="badge-in">In Network</span> : <span className="badge-out">Out of Network</span>}</td><td className="p-2">{i.expiration? (new Date(i.expiration)).toLocaleDateString() : ''}</td><td className="p-2">{days===null? 'No date' : (days<0? 'Expired' : `${days} days`)}</td><td className="p-2">{i.notes}</td></tr>) })}{insList.length===0 && <tr><td colSpan="7" className="p-4 text-slate-400">No insurances yet</td></tr>}</tbody></table></div></section></div>)}
