import React, { useEffect, useState } from 'react'
export default function InsurancesTable(){
  const empty = ()=>({ id:null, name:'', type:'PPO', doctor:'', doctorName:'', network:'In Network', expiration:'', notes:'' })
  const [list, setList] = useState([])
  const [doctors, setDoctors] = useState([])
  const [showModal, setShowModal] = useState(false)
  const [newIns, setNewIns] = useState(empty())
  useEffect(()=>{ setList(JSON.parse(localStorage.getItem('insuranceList')||'[]')); setDoctors(JSON.parse(localStorage.getItem('doctorsList')||'[]')) },[])
  useEffect(()=> localStorage.setItem('insuranceList', JSON.stringify(list)), [list])
  const add = ()=>{ if(!newIns.name) return alert('Enter name'); const id=Date.now().toString(); const item={...newIns,id}; if(newIns.doctor){ const doc=(JSON.parse(localStorage.getItem('doctorsList')||'[]')||[]).find(d=>d.id===newIns.doctor); if(doc) item.doctorName=doc.name } setList(prev=> [...prev,item]); setNewIns(empty()); setShowModal(false) }
  const remove = id=> setList(prev=> prev.filter(i=> i.id!==id))
  return (<div style={{background:'#0d1626',padding:12,borderRadius:8}}><h3>Insurances</h3><button className='btn' onClick={()=>setShowModal(true)}>+ Add Insurance</button><div style={{marginTop:12}}><table className='table'><thead><tr><th>Name</th><th>Type</th><th>Doctor</th><th>Expiration</th><th>Actions</th></tr></thead><tbody>{list.map(i=>(<tr key={i.id}><td>{i.name}</td><td>{i.type}</td><td>{i.doctorName}</td><td>{i.expiration? new Date(i.expiration).toLocaleDateString(): ''}</td><td><button onClick={()=>remove(i.id)} style={{color:'#f87171'}}>Delete</button></td></tr>))}{list.length===0 && <tr><td colSpan={5} style={{color:'#9ca3af'}}>No insurances yet</td></tr>}</tbody></table></div>{showModal && (<div className='modal-backdrop'><div className='modal'><h4>Add Insurance</h4><input placeholder='Insurance Name' value={newIns.name} onChange={e=>setNewIns({...newIns,name:e.target.value})} style={{display:'block',marginBottom:8}} /><select value={newIns.type} onChange={e=>setNewIns({...newIns,type:e.target.value})}><option>HMO</option><option>PPO</option><option>Medicare</option><option>Medicaid</option><option>Other</option></select><div style={{marginTop:8}}><select value={newIns.doctor||''} onChange={e=>setNewIns({...newIns,doctor:e.target.value})}><option value=''>Assign Doctor...</option>{doctors.map(d=>(<option key={d.id} value={d.id}>{d.name}</option>))}</select></div><div style={{marginTop:8}}><input type='date' value={newIns.expiration||''} onChange={e=>setNewIns({...newIns,expiration:e.target.value})} /></div><div style={{marginTop:8}}><textarea placeholder='Notes' value={newIns.notes} onChange={e=>setNewIns({...newIns,notes:e.target.value})} /></div><div style={{marginTop:12,display:'flex',gap:8,justifyContent:'flex-end'}}><button onClick={()=>setShowModal(false)} className='btn'>Cancel</button><button onClick={add} className='btn' style={{background:'#ef4444'}}>Save</button></div></div></div>)}</div>)
}
